import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import type { Lead } from "./types"
import { log } from "./logger"

/**
 * --apply-approved: read leads.json, pick status === "approved", and write
 * draft stubs to lib/data/bonuses.draft.ts (or creditCardBonuses.draft.ts).
 *
 * Draft files are NOT imported anywhere in the app. You copy approved entries
 * from them into the live lib/data files by hand, with any final edits.
 */

const LEADS_FILE = join(process.cwd(), "review-queue", "leads.json")
const DRAFTS = {
  bank_account_bonus: join(process.cwd(), "lib", "data", "bonuses.draft.ts"),
  credit_card_bonus: join(process.cwd(), "lib", "data", "creditCardBonuses.draft.ts"),
  brokerage_bonus: join(process.cwd(), "lib", "data", "brokerageBonuses.draft.ts"),
  other: join(process.cwd(), "lib", "data", "otherBonuses.draft.ts"),
} as const

export function applyApproved(): { wroteFiles: string[]; approvedCount: number } {
  if (!existsSync(LEADS_FILE)) {
    log("error", "apply.no_leads_file", { path: LEADS_FILE })
    return { wroteFiles: [], approvedCount: 0 }
  }
  const leads = JSON.parse(readFileSync(LEADS_FILE, "utf8")) as Lead[]
  const approved = leads.filter((l) => l.status === "approved")

  const byClass = new Map<keyof typeof DRAFTS, Lead[]>()
  for (const l of approved) {
    const key = (l.classification in DRAFTS ? l.classification : "other") as keyof typeof DRAFTS
    const arr = byClass.get(key) ?? []
    arr.push(l)
    byClass.set(key, arr)
  }

  const wrote: string[] = []
  for (const [cls, items] of byClass) {
    const path = DRAFTS[cls]
    const content = renderDraftFile(cls, items)
    writeFileSync(path, content)
    wrote.push(path)
  }
  return { wroteFiles: wrote, approvedCount: approved.length }
}

function renderDraftFile(cls: keyof typeof DRAFTS, leads: Lead[]): string {
  const stamp = new Date().toISOString()
  const header = [
    `/**`,
    ` * DRAFT — auto-generated by scripts/discover-bonuses/apply.ts`,
    ` * Generated: ${stamp}`,
    ` *`,
    ` * These entries have been APPROVED in the review queue but have NOT yet`,
    ` * been merged into the live data file. Review each, make any final edits,`,
    ` * then copy/paste into the corresponding live file (e.g. bonuses.ts).`,
    ` *`,
    ` * This file is NOT imported anywhere in the app.`,
    ` */`,
    ``,
    `export const drafts = [`,
  ]
  const body = leads.map(renderLead).join(",\n")
  const footer = [`]`, ``, `export const DRAFT_CLASSIFICATION = ${JSON.stringify(cls)}`, ``]
  return [...header, body, ...footer].join("\n")
}

function renderLead(l: Lead): string {
  // Emit a generic stub with the fields we have. Human fills in the rest.
  const obj = {
    id: suggestId(l),
    bank_name: l.bank,
    product_name: l.product,
    bonus_amount: l.bonus_amount,
    classification: l.classification,
    discovered_at: l.discovered_at,
    canonical_url: l.canonical_url,
    source_links: [l.canonical_url, ...l.source_urls].filter(Boolean),
    enrichment: l.enrichment,
    flags: l.flags,
    _discovery_confidence: l.confidence,
  }
  return "  " + JSON.stringify(obj, null, 2).replace(/\n/g, "\n  ")
}

function suggestId(l: Lead): string {
  const base = `${l.bank}-${l.product}-${l.bonus_amount ?? "x"}`
  return base
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64)
}
